<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Anush" failures="1" tests="1" name="Footer(failed)(failed)(failed)" time="24.813" errors="0" timestamp="15 May 2020 10:19:08 GMT">
  <testcase classname="Testcases.FooterLinks" name="footerLink" time="3.808">
    <failure type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException
at java.base/java.net.URL.<init>(URL.java:706)
at java.base/java.net.URL.<init>(URL.java:568)
at java.base/java.net.URL.<init>(URL.java:515)
at Testcases.FooterLinks.verify(FooterLinks.java:36)
at Testcases.FooterLinks.footerLink(FooterLinks.java:32)
Caused by: java.lang.NullPointerException
at java.base/java.net.URL.<init>(URL.java:612)
... 29 more
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- footerLink -->
</testsuite> <!-- Footer(failed)(failed)(failed) -->
